%% test_readtif.m  —  Validate readtif_custom against rasterio ground truth
%  Run this script in MATLAB from the Optimization/ directory.
%  It loads ref_tif_data.mat (generated by validate_readtif.py) and
%  compares readtif_custom output element-by-element against rasterio.
clear; clc;

tifs = {
    'Global_Wind_Net_Area_Add_Egrid.tif',   'Global_Wind_Net_Area_Add_Egrid'
    'Global_Wind_Fishnet_Area.tif',          'Global_Wind_Fishnet_Area'
    'Global_LandMask.tif',                   'Global_LandMask'
    'Global_fishnet.tif',                    'Global_fishnet'
    'Global_Solar_Net_Area_Add_Egrid.tif',   'Global_Solar_Net_Area_Add_Egrid'
    'Global_Solar_Fishnet_Area.tif',         'Global_Solar_Fishnet_Area'
    'Global_Grid_Division.tif',              'Global_Grid_Division'
};

load ref_tif_data.mat
n_ok = 0; n_fail = 0;

for i = 1:size(tifs,1)
    tif_file = tifs{i,1};
    ref_key  = tifs{i,2};
    try
        my_data  = readtif_custom(tif_file);
        ref_data = eval(ref_key);        %#ok<EVLC>

        [nr, nc] = size(ref_data);
        if isfloat(ref_data)
            err = max(abs(my_data(:) - ref_data(:)));
            ok  = err < 1e-12;
            tag = sprintf('max-abs-err=%.2e', err);
        else
            ok  = isequal(my_data, ref_data);
            tag = 'exact-match';
        end

        if ok
            fprintf('  OK       %-50s  %dx%d  %s\n', tif_file, nr, nc, tag);
            n_ok = n_ok + 1;
        else
            fprintf('  FAIL     %-50s  %dx%d  %s\n', tif_file, nr, nc, tag);
            n_fail = n_fail + 1;
        end
    catch ME
        fprintf('  ERROR    %-50s  %s\n', tif_file, ME.message);
        n_fail = n_fail + 1;
    end
end

fprintf('\n=== readtif_custom: %d passed, %d failed ===\n', n_ok, n_fail);

%% Also test the wrapper functions
fprintf('\n--- Testing geotiffread wrapper ---\n');
try
    d1 = geotiffread('Global_LandMask.tif');
    fprintf('  geotiffread(''Global_LandMask.tif''): %dx%d  OK\n', size(d1,1), size(d1,2));
catch ME
    fprintf('  geotiffread ERROR: %s\n', ME.message);
end

fprintf('\n--- Testing readgeoraster wrapper ---\n');
try
    [d2, R] = readgeoraster('Global_LandMask.tif');
    fprintf('  readgeoraster(''Global_LandMask.tif''): data=%dx%d  R=%s  OK\n', ...
        size(d2,1), size(d2,2), class(R));
catch ME
    fprintf('  readgeoraster ERROR: %s\n', ME.message);
end
