function [names, values] = build_diagnostics_vector(metrics)
% BUILD_DIAGNOSTICS_VECTOR — 从 metrics 结构体中提取诊断向量
%
% 输入：
%   metrics — evaluate_dispatch_and_cost 返回的结构体
%
% 输出：
%   names  — 诊断指标名称 cell 数组
%   values — 对应数值向量

    names = { ...
        'pv_capacity_gw', ...
        'wind_capacity_gw', ...
        'onshore_wind_capacity_gw', ...
        'offshore_wind_capacity_gw', ...
        'total_vre_capacity_gw', ...
        'selected_pv_grid_count', ...
        'selected_wind_grid_count', ...
        'gross_pv_generation_twh', ...
        'gross_wind_generation_twh', ...
        'gross_vre_generation_twh', ...
        'gross_vre_share', ...
        'base_load_twh', ...
        'flexible_generation_twh', ...
        'residual_vre_service_twh', ...
        'curtailed_vre_twh', ...
        'curtailment_rate', ...
        'total_load_twh', ...
        'transmission_capacity_tw', ...
        'vre_share', ...
        'flexible_ratio', ...
        'total_annual_cost' ...
    };

    values = [ ...
        metrics.pv_capacity_gw, ...
        metrics.wind_capacity_gw, ...
        metrics.onshore_wind_capacity_gw, ...
        metrics.offshore_wind_capacity_gw, ...
        metrics.total_vre_capacity_gw, ...
        metrics.selected_pv_grid_count, ...
        metrics.selected_wind_grid_count, ...
        metrics.gross_pv_generation_twh, ...
        metrics.gross_wind_generation_twh, ...
        metrics.gross_vre_generation_twh, ...
        metrics.gross_vre_share, ...
        metrics.base_load_twh, ...
        metrics.flexible_generation_twh, ...
        metrics.residual_vre_service_twh, ...
        metrics.curtailed_vre_twh, ...
        metrics.curtailment_rate, ...
        metrics.total_load_twh, ...
        metrics.transmission_capacity_TW, ...
        metrics.vre_share, ...
        metrics.flexible_ratio, ...
        metrics.total_annual_cost ...
    ];
end
