% test_select_preferred_solution — select_preferred_solution 单元测试

fprintf('=== 测试 select_preferred_solution ===\n');

%% 测试 1：bounded_transition 模式（SSP1-2.6 / SSP2-4.5）
fprintf('\n--- 测试 1：bounded_transition ---\n');

prs = [
    0.10, 0.40, 100;  % vre = 1 - 0.20 - 0.40 = 0.40，低于下界
    0.14, 0.30, 120;  % vre = 0.50，合格
    0.12, 0.28, 130;  % vre = 0.52，合格但成本更高
    0.16, 0.25,  80;  % 弃电率超过 15%
    0.11, 0.05,  60;  % vre = 0.75，超过上界
];

result = select_preferred_solution( ...
    prs, ...
    0.20, ...
    0.45, ...
    0.60, ...
    0.15, ...
    'bounded_transition' ...
);

assert(result.sol_idx == 2, ...
    sprintf('测试1失败：期望 sol_idx=2，实际 sol_idx=%d', result.sol_idx));
assert(strcmp(result.status, 'qualified'), ...
    sprintf('测试1失败：期望 status=qualified，实际 status=%s', result.status));
assert(result.n_qualified == 2, ...
    sprintf('测试1失败：期望 n_qualified=2，实际 n_qualified=%d', result.n_qualified));
fprintf('测试 1 通过：bounded_transition 选中解 %d\n', result.sol_idx);

%% 测试 2：fossil_upper_bound 模式（SSP5-6.0）
fprintf('\n--- 测试 2：fossil_upper_bound ---\n');

prs2 = [
    0.10, 0.72, 100;  % vre = 0.10，合格
    0.14, 0.70,  80;  % vre = 0.12，合格且成本最低
    0.12, 0.65,  60;  % vre = 0.17，超过上限
    0.16, 0.73,  50;  % 弃电率超过 15%
];

result2 = select_preferred_solution( ...
    prs2, ...
    0.18, ...
    NaN, ...
    0.13, ...
    0.15, ...
    'fossil_upper_bound' ...
);

assert(result2.sol_idx == 2, ...
    sprintf('测试2失败：期望 sol_idx=2，实际 sol_idx=%d', result2.sol_idx));
assert(result2.n_qualified == 2, ...
    sprintf('测试2失败：期望 n_qualified=2，实际 n_qualified=%d', result2.n_qualified));
fprintf('测试 2 通过：fossil_upper_bound 选中解 %d\n', result2.sol_idx);

%% 测试 3：无合格解应明确报错
fprintf('\n--- 测试 3：无合格解报错 ---\n');

prs3 = [
    0.20, 0.80, 100;  % 弃电率超过 15%，vre 超过上界
    0.18, 0.75,  90;  % 弃电率超过 15%
    0.10, 0.05,  80;  % vre = 0.75，远超上界
];

try
    select_preferred_solution( ...
        prs3, ...
        0.20, ...
        0.45, ...
        0.60, ...
        0.15, ...
        'bounded_transition' ...
    );
    error('测试3失败：应当抛出异常');
catch ME
    assert(contains(ME.message, '不存在合格 preferred solution'), ...
        sprintf('测试3失败：错误消息不匹配，实际为：%s', ME.message));
    fprintf('测试 3 通过：无合格解正确报错\n');
end

%% 测试 4：fossil_upper_bound 模式下所有解超过弃电率上限
fprintf('\n--- 测试 4：fossil_upper_bound 全部超弃电率 ---\n');

prs4 = [
    0.20, 0.72, 100;
    0.18, 0.70,  80;
];

try
    select_preferred_solution( ...
        prs4, ...
        0.18, ...
        NaN, ...
        0.12, ...
        0.15, ...
        'fossil_upper_bound' ...
    );
    error('测试4失败：应当抛出异常');
catch ME
    assert(contains(ME.message, '不存在合格 preferred solution'), ...
        sprintf('测试4失败：错误消息不匹配，实际为：%s', ME.message));
    fprintf('测试 4 通过：fossil_upper_bound 无合格解正确报错\n');
end

fprintf('\n=== 全部测试通过 ===\n');
